### ISSUE TITLE
Assignment #1 - activate github pages

### ISSUE THREAD

**Issue by msteitle** [TheCatBomb10/all-about-computer-games#2]
We want to make your webpage accessible from the world wide web in all its wideness. To do this, we will use Github Pages.

1. Read up on how to activate this at https://pages.github.com
1. Back in your repository, you will go to the Settings page and scroll down until you find the Github Pages options.
1. Set the source branch as `master`
1. Choose a theme, and when you commit, commit to a branch named to your choosing (as opposed to committing straight to `master`)

Your final task is to find and load the _url_ for your github pages site. _Hint: it is in the github pages section of the repository Settings)_

**When you are done, comment on this issue below with the url of your website.**

Good luck!

**Comment by TheCatBomb10** [comment]
https://thecatbomb10.github.io/all-about-computer-games/

**Comment by msteitle** [comment]
Looks good! Great job!
